language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
install:
  - "npm list -g grunt-cli --depth=0 || npm install -g grunt-cli"
  - "npm install"
script:
  - 'grunt spec'
cache:
  directories:
    - "node_modules"
    - $(npm config get prefix)/bin/grunt-cli
